config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  get 'tweets/new' => 'tweets#new',  as: :new_tweet

  get 'tweets/:id' => 'tweets#show', as: :tweet

  post 'tweets/new' => 'tweets#create', as: :tweets

  post 'tweets/:id/like' => 'tweets#like', as: :like_tweet

  get 'tweets/:id/edit' => 'tweets#edit', as: :edit_tweet

  patch 'tweets/:id' => 'tweets#update'

  get 'tweets/:id/delete' => 'tweets#delete', as: :delete_tweet

  get "/sign_in" => "sessions#new", as: :sign_in

  post "/sign_in" => 'sessions#create'

  post "/sign_out" => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up

 post "/users" => 'users#create', as: :users

 post "/users/:id/follow" => "following#create", as: :follow_user

  post "/users/:id/stop-following" => "following#delete", as: :stop_following_user

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

 belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
   has_many :tweets
   acts_as_followable
   acts_as_follower

  def full_name
    [last_name, first_name].join(", ")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  before_action do
     @current_user = User.find_by id: session[:user_id]
   end

   def authenticate_user!
     if @current_user.blank?
       redirect_to sign_in_path, notice: "Please Sign In"
     end

   end

   def sign_in user
     session[:user_id] = user.id
   end

   def sign_out
     session.delete :user_id
   end

   def user_signed_in?
     @current_user.present?
   end
   helper_method :user_signed_in?




end

app/controllers/following_controller.rb
class FollowingController < ApplicationController


  before_action :authenticate_user!

   def create
     new_user = User.find params[:id]
     @current_user.follow new_user
     redirect_to root_path, notice: "You have followed #{new_user.full_name}"
   end

   def delete
     new_user = User.find params[:id]
     @current_user.stop_following new_user
     redirect_to root_path, notice: "You have stopped following #{new_user.full_name}"

   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  

   def create

     # get email/pw from form
     email = params[:email]
     password = params[:password]
     # find user from the email
     user = User.find_by email: email
     # authenticate the password
     if user.present? && user.authenticate(password)
       # session & redirect or render
       sign_in user
       redirect_to root_path
     else
       flash.now[:alert] =  "Something is wrong with your email or password. Try gain."
       render :new
     end

   end

   def delete
     sign_out
     redirect_to root_path, notice: "You are now signed out. Thank you come again"
   end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


  before_action :authenticate_user!

  def index
    @users = User.where("id != ?", @current_user.id)
    group = @current_user.following_users

   follower_ids = group.pluck(:id)
   all_ids = follower_ids << @current_user.id
    @people = Tweet.where(user_id: all_ids).order("post_at DESC")
  end


  def show
    @tweet = Tweet.find params[:id]

  end

  def new
     @tweet = Tweet.new
  end

  def create
   @tweet = Tweet.new tweet_params
   @tweet = @current_user
   if @tweet.save
     redirect_to root_path
   else
     render :new
   end
 end

  def edit
    @tweet = @current_user.tweets.find params[:id]

  end

  def update
    @tweet = @current_user.tweets.find params[:id]
   if @tweet.update params.require(:tweet).permit(:text)
     redirect_to root_path
   else
     render :edit
   end
 end


  def delete
    @tweet = @current_user.tweets.find params[:id]
    # @tweet = Tweet.find params[:id]
    @tweet.destroy
    redirect_to root_path
  end


  def like
      @tweet = Tweet.find params[:id]
      @tweet.update view_count: (@tweet.view_count + 1)
      redirect_to root_path
    end

    def tweet_params
     params.require(:tweet).permit(:text, :user_id)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
     @user = User.new
   end

   def create
     @user = User.new params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
     if @user.save
       sign_in @user
       redirect_to root_path, notice: "Welcome to my_twitter, #{@user.full_name}"
     else
       render :new
     end
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

  <nav class="libold">
    <ul class="nav nav-tabs nav-justified">

     <% if user_signed_in? %>
       <li> <%= link_to 'MyTwitter' %> </li>
       <li> <%= link_to 'Home', root_path %></li>
       <li> <%= link_to 'New Tweet', new_tweet_path %></li>
       <li><%= link_to 'Sign Out', sign_out_path, method: :post %></li>
       <% end %>

   </ul>
 </nav>
 <div class="page-header">
   <h1>MyTwitter <small>Share you thought...</small></h1>
 </div>




  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <% if notice %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>



<%= yield %>


</body>
</html>

app/views/tweets/delete.html.erb
<h1>Tweets#delete</h1>
<p>Find me in app/views/tweets/delete.html.erb</p>

app/views/tweets/edit.html.erb
<div class="container col-md-6 col-md-offset-3">
  <div class="form2">
<h1>Edit Tweet</h1>

<%= simple_form_for @tweet do |f| %>
 <%= f.input :text, as: :text %>

 <%= f.button :submit %>
<% end %>
</div>
</div>

app/views/tweets/index.html.erb
<div class="container col-md-6 col-md-offset-3">


<h1>MyTwitter</h1>
<div class="Welcome"> Welcome <%= @current_user.full_name %> </div>
<% @people.each do |tweet| %>
<hr>

<blockquote class="tests">
  <%= image_tag(tweet.user.photo) %> <h3 class="fullname"> <%= tweet.user.full_name %></h3>
  <%=  link_to truncate(tweet.text,length: 140), tweet_path(id: tweet.id) %> <cite><%= tweet.post_at %></cite>


  <%= link_to like_tweet_path(id: tweet.id), method: :post, class: 'btn btn-default' do %>
      <i class="fa fa-star-o"></i>
      <%= pluralize tweet.view_count, 'like' %>
      <% end %>

</blockquote>
<hr>
<% end %>
</div>


<div class="test col-xs-3 fixed-top">
<div class="list-group">
  <a href="#" class="list-group-item active">
    frienemies
  </a>
  <% @users.each do |user| %>
  <div class="list-group-item">
     <% if @current_user.following? user %>
      <%= link_to "Stop Following #{user.full_name}", stop_following_user_path(id: user.id), method: :post %>
    <% else %>
      <%= link_to "Follow #{user.full_name}", follow_user_path(id: user.id), method: :post %>
    <% end %>
</div>
<% end %>
</div>
</div>

app/views/tweets/new.html.erb
<br>



<div class="container col-md-6 col-md-offset-3">
  <div class="form2">
<h1>Enter New Tweet</h1>



 <%= simple_form_for @tweet do |f| %>
 <%= f.input :text, as: :text %>
 <%= f.button :submit %>
<% end %>
</div>
</div>

app/views/tweets/show.html.erb
<div class="container">
 <div class="show">
   <br>
<%= image_tag(@tweet.user.photo) %> <h3> <%= @tweet.user.full_name %></h3>
 </div>
<hr>
<blockquote>

  <%= @tweet.text %> <cite><%= @tweet.post_at %></cite>

  <%= link_to like_tweet_path(id: @tweet.id), method: :post, class: 'btn btn-default' do %>
      <i class ="glyphicon glyphicon-thumbs-up"></i>
      <%= pluralize @tweet.view_count, 'like' %>
      <% end %>

   <% if @current_user == @tweet.user %>
      <%= link_to 'Edit', edit_tweet_path %> or <%= link_to 'Delete', delete_tweet_path, method: :get, data: {confirm: "Are you sure?"} %>
   <% end %>
</blockquote>

<hr>
</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">

<%= simple_form_for @user do |f| %>
 <%= f.input :first_name %>
 <%= f.input :last_name %>
 <%= f.input :email %>
 <%= f.input :password %>
 <%= f.input :password_confirmation, label: "Password Confirmation" %>
 <%= f.submit "Sign Up", class: "btn btn-primary btn-block btn-lg" %>
<% end %>

</div>